server:
  port: 28888
  compression:
        enabled: true
        min-response-size: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:25555/eureka/
spring:
  application:
          name: ribbon-consumer